
package Vistas;

import Logic.command.DeleteUser;
import Logic.command.UpdateUser;
import Model.User;
import database.CConexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author juand
 */
public class GestiónUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public GestiónUsuarios() {
        initComponents();
        setLocationRelativeTo (null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnActualizar = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        BtnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboRoles = new javax.swing.JComboBox<>();
        TxtNombre = new javax.swing.JTextField();
        TxtApellido = new javax.swing.JTextField();
        TxtNumerCelular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        users = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Gestión Administrativa de Usuarios");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 36));

        BtnActualizar.setBackground(new java.awt.Color(255, 102, 0));
        BtnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 30));

        BtnBorrar.setBackground(new java.awt.Color(255, 51, 51));
        BtnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnBorrar.setText("Borrar");
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 140, 30));

        BtnIngresar.setBackground(new java.awt.Color(255, 255, 255));
        BtnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnIngresar.setForeground(new java.awt.Color(0, 0, 0));
        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 140, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 69, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 77, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Número Celular");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cédula");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 61, -1));

        ComboRoles.setBackground(new java.awt.Color(255, 255, 255));
        ComboRoles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ComboRoles.setForeground(new java.awt.Color(0, 0, 0));
        ComboRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un rol", "Cliente", "Repartidor" }));
        jPanel2.add(ComboRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 580, 50));

        TxtNombre.setBackground(new java.awt.Color(255, 255, 255));
        TxtNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtNombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 260, 31));

        TxtApellido.setBackground(new java.awt.Color(255, 255, 255));
        TxtApellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtApellido.setForeground(new java.awt.Color(0, 0, 0));
        TxtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(TxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 260, 31));

        TxtNumerCelular.setBackground(new java.awt.Color(255, 255, 255));
        TxtNumerCelular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtNumerCelular.setForeground(new java.awt.Color(0, 0, 0));
        TxtNumerCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumerCelularActionPerformed(evt);
            }
        });
        jPanel2.add(TxtNumerCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 260, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Roles");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtIdUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtIdUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIdUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 260, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Contraseña");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, 30));

        users.setBackground(new java.awt.Color(255, 255, 255));
        users.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        users.setForeground(new java.awt.Color(0, 0, 0));
        users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cedula", "Nombre", "Apellido", "Telefono", "Roles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(users);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 920, 190));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\juand\\OneDrive\\Desktop\\SafeTracking\\src\\main\\java\\Resources\\Imagenes\\Simple Lined White Login Page Wireframe Website UI Prototype.png")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 920, 570));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\juand\\OneDrive\\Desktop\\SafeTracking\\src\\main\\java\\Resources\\Imagenes\\UI Login Page Desktop Prototype (1).png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1010, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
         try {
        
        int id = Integer.parseInt(txtIdUsuario.getText());

        
        if (txtIdUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa el ID del usuario.");
            return;
        }

       
        User user = getUserById(id);

       
        if (user != null) {
            TxtNombre.setText(user.getNome());
            TxtApellido.setText(user.getLastName());
            TxtNumerCelular.setText(user.getPhone());
            txtPassword.setText(user.getPassword());
            txtIdUsuario.setText(user.getIdUser());
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el usuario con el ID proporcionado.");
            return;
        }

        String nombre=TxtNombre.getName();
        String apellido = TxtApellido.getText();
        String password = new String(txtPassword.getPassword());
        String telefono = TxtNumerCelular.getText();
        String idUsuario = txtIdUsuario.getText();

        // Validar que los campos no estén vacíos
        if (nombre.isEmpty() || apellido.isEmpty() || password.isEmpty() || telefono.isEmpty() || idUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos.");
            return;
        }

        
        user.setNome(nombre);
        user.setLastName(apellido);
        user.setPassword(password);
        user.setPhone(telefono);
        user.setIdUser(idUsuario);

        
        UpdateUser updateUser = new UpdateUser();
        updateUser.update(user);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID debe ser un número válido.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar el usuario: " + e.getMessage());
    }
}

// Método para obtener los datos del usuario a partir del ID
private User getUserById(int id) {
    // Aquí deberías implementar la lógica para obtener el usuario desde la base de datos.
    // Puedes hacer una consulta SQL para buscar al usuario con el ID proporcionado.
    // Por ejemplo:

    // Supongamos que tienes una clase `UserDAO` para manejar la base de datos:
    User user = null;
    try {
        Connection cx = CConexion.conecarDB();
        String query = "SELECT * FROM users WHERE id = ?";
        PreparedStatement ps = cx.prepareStatement(query);
        ps.setInt(1, id);
        ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            user = new User();
            user.setId(rs.getInt("id"));
            user.setNome(rs.getString("name"));
            user.setLastName(rs.getString("lastname"));
            user.setPassword(rs.getString("password"));
            user.setPhone(rs.getString("phone"));
            user.setIdUser(rs.getString("idUser"));
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al obtener el usuario: " + e.getMessage());
    }
    return user;
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        try {
        String idUsuario = txtIdUsuario.getText().trim();  
        if (idUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese el ID (Cédula) del usuario a eliminar.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas eliminar este usuario?", 
                                                     "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            deleteUserById(idUsuario);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error al eliminar el usuario: " + ex.getMessage());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Se produjo un error inesperado: " + ex.getMessage());
    }
}
private void deleteUserById(String idUsuario) throws SQLException {

    Connection cx = CConexion.conecarDB();

    String deleteQuery = "DELETE FROM users WHERE idUser = ?";

    try (PreparedStatement ps = cx.prepareStatement(deleteQuery)) {
        ps.setString(1, idUsuario);  

        int rowsAffected = ps.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Usuario eliminado con éxito.");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró un usuario con ese ID.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al eliminar el usuario: " + e.getMessage());
        throw e; 
    } finally {

        try {
            if (cx != null && !cx.isClosed()) {
                cx.close();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_BtnBorrarActionPerformed

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void TxtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApellidoActionPerformed

    private void TxtNumerCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumerCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumerCelularActionPerformed

    private void txtIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestiónUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestiónUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestiónUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestiónUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestiónUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JComboBox<String> ComboRoles;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtNumerCelular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTable users;
    // End of variables declaration//GEN-END:variables
}
