/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author juand
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnVentanaIniciar = new javax.swing.JButton();
        BtnVentanaRegistrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BtnCliente = new javax.swing.JButton();
        BtnAdministrador = new javax.swing.JButton();
        BtnRepartidor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtContraseña = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Iniciar Sesión");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 240, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Accede a tu cuenta según tu rol");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 230, 24));

        BtnVentanaIniciar.setBackground(new java.awt.Color(255, 255, 255));
        BtnVentanaIniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnVentanaIniciar.setForeground(new java.awt.Color(0, 0, 0));
        BtnVentanaIniciar.setText("Iniciar Sesión");
        BtnVentanaIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentanaIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVentanaIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 130, 140, 30));

        BtnVentanaRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        BtnVentanaRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnVentanaRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        BtnVentanaRegistrar.setText("Registrarse");
        BtnVentanaRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentanaRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVentanaRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Selecciona tu rol");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        BtnCliente.setBackground(new java.awt.Color(255, 255, 255));
        BtnCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCliente.setForeground(new java.awt.Color(0, 0, 0));
        BtnCliente.setText("Cliente");
        BtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClienteActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 80, 30));

        BtnAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        BtnAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAdministrador.setForeground(new java.awt.Color(0, 0, 0));
        BtnAdministrador.setText("Administrador");
        jPanel1.add(BtnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, 30));

        BtnRepartidor.setBackground(new java.awt.Color(255, 255, 255));
        BtnRepartidor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnRepartidor.setForeground(new java.awt.Color(0, 0, 0));
        BtnRepartidor.setText("Repartidor");
        jPanel1.add(BtnRepartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Correo Electrónico");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        TxtEmail.setBackground(new java.awt.Color(255, 255, 255));
        TxtEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtEmail.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 380, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, 20));

        TxtContraseña.setBackground(new java.awt.Color(255, 255, 255));
        TxtContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtContraseña.setForeground(new java.awt.Color(0, 0, 0));
        TxtContraseña.setText("jPasswordField1");
        jPanel1.add(TxtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 380, 30));

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Iniciar Sesión");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 390, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\juand\\OneDrive\\Imágenes\\Simple Lined White Login Page Wireframe Website UI Prototype.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 510, 520));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\juand\\OneDrive\\Imágenes\\UI Login Page Desktop Prototype (1).png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 660, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnClienteActionPerformed

    private void BtnVentanaIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentanaIniciarActionPerformed
         // Asumiendo que la autenticación fue exitosa
    Login ventanaLogin  = new Login ();
    ventanaLogin .setVisible(true);
    this.dispose(); // Cierra la ventana de login
    }//GEN-LAST:event_BtnVentanaIniciarActionPerformed

    private void BtnVentanaRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentanaRegistrarActionPerformed
        // Asumiendo que la autenticación fue exitosa
    Registro ventanaRegistro = new Registro();
    ventanaRegistro.setVisible(true);
    this.dispose(); // Cierra la ventana de login
    }//GEN-LAST:event_BtnVentanaRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdministrador;
    private javax.swing.JButton BtnCliente;
    private javax.swing.JButton BtnRepartidor;
    private javax.swing.JButton BtnVentanaIniciar;
    private javax.swing.JButton BtnVentanaRegistrar;
    private javax.swing.JPasswordField TxtContraseña;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
